#!/bin/bash
 
echo "--------------------------------------------------"
echo "               Històric d’Oscars"
echo "-------------------------------------------------- "
echo "1.1 Mostrar històric d’Oscars a millor actor (alfabètic)."
echo "1.2 Mostrar històric d’Oscars a millor actriu (edat)"
echo "1.3 Mostrar històric d’Oscars (actors/actrius)."
 
 
read a
 
case $a in
1.1)

;;



1.2)


 ;;
1.3) 

i=2
max=`wc -l < oscar_age_male.csv`

while [ $i -lt $max ]     
do
any=`cat oscar_age_male.csv | tail +1 |sort -k2 -t, | head -$i | tail -1| cut -d, -f2`
actor=`cat oscar_age_male.csv | tail +1 |sort -k2 -t, | head -$i | tail -1| cut -d'"' -f2`
edat=`cat oscar_age_male.csv | tail +1 |sort -k2 -t, | head -$i | tail -1| cut -d, -f3`
pelicula=`cat oscar_age_male.csv | tail +1 |sort -k2 -t, | head -$i | tail -1| cut -d'"' -f4`

actriu=`cat oscar_age_female.csv | tail +1 |sort -k2 -t, | head -$i | tail -1| cut -d'"' -f2`
edat2=`cat oscar_age_female.csv | tail +1 |sort -k2 -t, | head -$i | tail -1| cut -d, -f3`
pelicula2=`cat oscar_age_female.csv | tail +1 |sort -k2 -t, | head -$i | tail -1| cut -d'"' -f4`

echo any: $any
echo actor: $actor
echo edat: $edat
echo pel·licula: $pelicula
echo actriu: $actriu
echo edat: $edat2
echo pel·licula: $pelicula2
echo -------------------------------------------------------------
let i=i+1;
done
 ;;

*) 
echo "error";;
esac
