#!/bin/bash
 
 
echo --------------------------------------------------
echo			Qui va guanyar ...?
echo --------------------------------------------------
echo 2.1 Mostrar l’actor i l’actriu que van guanyar un any determinat. 
echo 2.2 Mostrar els Oscars a millor actriu guanyats per una actriu determinada. 
echo 2.3 Mostrar els Oscars a millor actriu o actor que ha obtingut una pel·lícula determinada.
 
echo ""
echo Escollir opció
read opcio
 
case $opcio in
 
 2.1)
 ;;
 
 2.2)
;;
 
 
2.3)
echo Introduiex pel·lícula:
read peli
 
Any=`tail +2 oscar_age_female.csv | grep -i "$peli" | cut -d, -f2`
any=`tail +2 oscar_age_male.csv | grep -i "$peli" | cut -d, -f2`
 
actriu=`tail +2 oscar_age_female.csv | grep -i "$peli" | cut -d '"' -f2`
actor=`tail +2 oscar_age_male.csv | grep -i "$peli" | cut -d '"' -f2`
edatfemale=`tail +2 oscar_age_female.csv | grep -i "$peli" | cut -d, -f3`
edatmale=`tail +2 oscar_age_male.csv | grep -i "$peli" | cut -d, -f3`
 
echo ""
echo Oscars a millor actriu i actor obtinguts per: 
echo $peli
echo Any: $Any $any
echo ----------------------------------------------
echo actriu: $actriu
echo edat: $edatfemale
echo actor: $actor
echo edat: $edatmale
;;
 
*);;
 
 esac 
