#!/bin/bash
 
 
echo --------------------------------------------------
echo			Qui va guanyar ...?
echo --------------------------------------------------
echo 2.1 Mostrar l’actor i l’actriu que van guanyar un any determinat. 
echo 2.2 Mostrar els Oscars a millor actriu guanyats per una actriu determinada. 
echo 2.3 Mostrar els Oscars a millor actriu o actor que ha obtingut una pel·lícula determinada.
 
echo ""
echo Escollir opció
read opcio
 
case $opcio in
 
 2.1)
  echo Selecciona any: 
 
 read any
 
 male=`tail +2 oscar_age_male.csv | grep "^[a-z,A-Z,0-9, ]*, $any" | cut -d'"' -f2 ` 
 
 
 agemale=`tail +2 oscar_age_male.csv | grep "^[a-z,A-Z,0-9, ]*, $any" | cut -d, -f3 `
 
 peliculamale=`tail +2 oscar_age_male.csv | grep "^[a-z,A-Z,0-9, ]*, $any" | cut -d'"' -f4`
 
 female=`tail +2 oscar_age_female.csv | grep "^[a-z,A-Z,0-9, ]*, $any" | cut -d'"' -f2 `
 
  agefemale=`tail +2 oscar_age_female.csv | grep "^[a-z,A-Z,0-9, ]*, $any" | cut -d, -f3 `
 
 peliculafemale=`tail +2 oscar_age_female.csv | grep "^[a-z,A-Z,0-9, ]*, $any" | cut -d'"' -f4`
 
 echo ""
 echo "Guanyadors any $any"
 echo ""
 echo "Oscar a millor actor: $male"
 echo ""
 echo "Edat: $agemale"
 echo ""
 echo "Pel·lícula: $peliculamale"
 echo " "
 echo --------------------------------------------------
 echo ""
 echo "Oscar a millor actriu: $female"
 echo ""
 echo "Edat: $agefemale"
 echo ""
 echo "Pel·lícula: $peliculafemale"
 echo " "
 echo ""

 ;;

 
 2.2)

 echo Introdueix un nom actriu:
 
 
 read actriu
 
ageFemale=`tail +2 oscar_age_female.csv | grep -i "$actriu"|cut -d, -f3 >EDATGUANYADORES`

year=`tail +2 oscar_age_female.csv | grep -i "$actriu"|cut -d, -f2 >ANYVICTORIA`
 
movie=`tail +2 oscar_age_female.csv | grep -i "$actriu"|cut -d'"' -f4 >PELÍCUL·LA`
 
 
guanyadoraoscar=`paste EDATGUANYADORES ANYVICTORIA > EDATIANYS`
guanyadoraoscar2=`paste EDATIANYS PELÍCUL·LA > FINAL`
 
echo Edat> Edat
echo Any> Any
echo Pel·lícula> Pel·lícula
 
EdatAny=`paste Edat Any > EdatAny`
 

FinalTitol=`paste EdatAny Pel·lícula>TITOL`
 
echo --------------------------->>TITOL
 
 
 echo ""
 echo "Oscars a millor actriu obtinguts per: $actriu" 
 echo ""
 
cat TITOL	 
 
echo ""
 
cat FINAL

;;


2.3)
echo Introduiex pel·lícula:
read peli
 
Any=`tail +2 oscar_age_female.csv | grep -i "$peli" | cut -d, -f2`
any=`tail +2 oscar_age_male.csv | grep -i "$peli" | cut -d, -f2`
 
actriu=`tail +2 oscar_age_female.csv | grep -i "$peli" | cut -d '"' -f2`
actor=`tail +2 oscar_age_male.csv | grep -i "$peli" | cut -d '"' -f2`
edatfemale=`tail +2 oscar_age_female.csv | grep -i "$peli" | cut -d, -f3`
edatmale=`tail +2 oscar_age_male.csv | grep -i "$peli" | cut -d, -f3`
 
echo ""
echo Oscars a millor actriu i actor obtinguts per: 
echo $peli
echo Any: $Any $any
echo ----------------------------------------------
echo actriu: $actriu
echo edat: $edatfemale
echo actor: $actor
echo edat: $edatmale
;;
 
*);;
 
 esac 
